name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: /dev/shm/cargo-target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build Binary
      run: cargo build --release

    - name: Copy Binary From SHM
      run: |
        mkdir -p ./output
        cp /dev/shm/cargo-target/release/rust_test_shm ./output/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-binary
        path: ./output/rust_test_shm
